# Propiedades de conexión para ejecución local (fuera de Docker)
url=jdbc:postgresql://localhost:5432/mgbd_db
username=mgbd_user
password=mgbd_pass
changeLogFile=db/changelog/db.changelog-master.yaml
